export type PanelChartConfig = {
  title?: string;
  color?: string;
  renderMode?: "canvas" | "svg";
  xAxisName?: string;
  yAxisName?: string;
  xAxisTickShow?: boolean;
  yAxisTickShow?: boolean;
  xAxisTickColor?: string;
  yAxisTickColor?: string;
  xAxisSplitLineShow?: boolean;
  yAxisSplitLineShow?: boolean;
  xAxisSplitLineColor?: string;
  yAxisSplitLineColor?: string;
  xAxisLabelColor?: string;
  yAxisLabelColor?: string;
  xAxisLabelFontSize?: number;
  yAxisLabelFontSize?: number;
  xAxisLabelAutoEllipsis?: boolean;
  yAxisLabelAutoEllipsis?: boolean;
  tooltipShow?: boolean;
  tooltipTrigger?: "axis" | "item";
  tooltipBackgroundColor?: string;
  tooltipTextColor?: string;
  tooltipFormatter?: string;
  labels?: string[];
  values?: number[];
  smooth?: boolean;
  barWidth?: number;
  pieInnerRadius?: number;
  pieOuterRadius?: number;
  option?: Record<string, unknown>;
};

export type PanelElementStyle = {
  backgroundColor?: string;
  backgroundImage?: string;
  backgroundImageRemoteUrl?: string;
  backgroundSize?: string;
  backgroundPosition?: string;
  borderWidth?: number;
  borderStyle?: "none" | "solid" | "dashed" | "dotted" | "double";
  borderColor?: string;
  borderRadius?: number;
};

export type ReferenceCopyMode = "shallow" | "deep";

export type PanelElement = {
  id: string;
  layerId: string;
  zIndex?: number;
  name?: string;
  locked?: boolean;
  materialType?: string;
  refLayerId?: string;
  refCopyMode?: ReferenceCopyMode;
  refSnapshot?: PanelElement[];
  chart?: PanelChartConfig;
  textHtml?: string;
  textAllowInput?: boolean;
  textFontFamily?: string;
  textFontSize?: number;
  textFontWeight?: string;
  textColor?: string;
  textLineHeight?: number;
  textAlign?: "left" | "center" | "right" | "justify";
  gridRows?: number;
  gridCols?: number;
  gridGap?: number;
  gridPadding?: number;
  gridSnapThreshold?: number;
  parentGridId?: string;
  gridSlotIndex?: number;
  mappingSourceNodeId?: string;
  mappingSourceLayerId?: string;
  audioSrc?: string;
  audioRemoteUrl?: string;
  audioPosterImage?: string;
  audioIconPreset?: "speaker" | "music" | "headphone" | "wave";
  audioVisualEffect?: "none" | "pulse" | "ripple";
  audioVisualSpeed?: "slow" | "normal" | "fast";
  mediaAutoPauseOnEdit?: boolean;
  videoSrc?: string;
  videoRemoteUrl?: string;
  style?: PanelElementStyle;
  x: number;
  y: number;
  width: number;
  height: number;
  rotate?: number;
};

